import { Alert, Button, Card, Col, Divider, Form, Input, InputNumber, Row, Select, Space, Statistic, Table, Typography, message } from "antd";
import { useEffect, useMemo, useRef, useState } from "react";
import { api, Candidate, Loadout, LoadoutPayload, NamedID, Summary, User } from "./api";
import { SearchOption, SearchSelect } from "./SearchSelect";

const slots=["weapon","head","chest","arms","waist","legs"] as const;type Slot=typeof slots[number];
const slotNames:Record<Slot,string>={weapon:"武器",head:"头部",chest:"胸部",arms:"腕部",waist:"腰部",legs:"腿部"};
type PieceState={equipment:SearchOption<Candidate>|null;decorations:Array<SearchOption<Candidate>|null>};
const emptyPieces=()=>Object.fromEntries(slots.map(slot=>[slot,{equipment:null,decorations:[null,null,null]}])) as Record<Slot,PieceState>;
const candidateOption=(row:Candidate):SearchOption<Candidate>=>({key:`${row.save_type??0}:${row.save_id}`,label:row.name,description:`${row.english} · ID ${row.save_id} · ${row.slots}孔`,value:row});
const namedOption=(row:NamedID):SearchOption<NamedID>=>({key:row.id,label:row.name,description:`${row.english} · ID ${row.id}`,value:row});
const noneSkillOption:SearchOption<NamedID>={key:0,label:"无",description:"None · ID 0",value:{id:0,name:"无",english:"None"}};
const storedDecorations=(ids:number[]):Array<SearchOption<Candidate>|null>=>{const values:Array<SearchOption<Candidate>|null>=ids.map(id=>({key:id,label:`装饰珠 ID ${id}`,value:{save_id:id,name:`ID ${id}`,english:"",slots:0,confirmed:true}}));while(values.length<3)values.push(null);return values.slice(0,3)};

export function LoadoutEditor({users,initial,onDone,onCancel}:{users:User[];initial?:Loadout;onDone:()=>void;onCancel:()=>void}){
  const[title,setTitle]=useState(initial?.name??"");const[remark,setRemark]=useState(initial?.remark??"");const[gender,setGender]=useState<"male"|"female">(initial?.payload?.gender??"male");const[status,setStatus]=useState(initial?.status==="hidden"?"hidden":"published");const[owner,setOwner]=useState(initial?.owner_user_id??users[0]?.id??"");const[dataVersion,setDataVersion]=useState(initial?.data_version??"");const[pieces,setPieces]=useState<Record<Slot,PieceState>>(emptyPieces);const[charmClasses,setCharmClasses]=useState<NamedID[]>([]);const[charmClass,setCharmClass]=useState(initial?.payload?.charm.class_id??1);const[charmSlots,setCharmSlots]=useState(initial?.payload?.charm.slots??0);const[skill1,setSkill1]=useState<SearchOption<NamedID>|null>(noneSkillOption);const[skill2,setSkill2]=useState<SearchOption<NamedID>|null>(noneSkillOption);const[points1,setPoints1]=useState(initial?.payload?.charm.skill1_points??0);const[points2,setPoints2]=useState(initial?.payload?.charm.skill2_points??0);const[charmDecorations,setCharmDecorations]=useState<Array<SearchOption<Candidate>|null>>([null,null,null]);const[summary,setSummary]=useState<Summary|null>(initial?.risk_summary??null);const[saving,setSaving]=useState(false);const[saveError,setSaveError]=useState("");const previewGeneration=useRef(0);
  useEffect(()=>{void api<{data_version:string}>("/admin/game-data/mh3g/meta").then(value=>setDataVersion(value.data_version));void api<{items:NamedID[]}>("/admin/game-data/mh3g/charm-classes").then(value=>setCharmClasses(value.items))},[]);
  useEffect(()=>{if(!initial?.payload)return;const payload=initial.payload;const next=emptyPieces();for(const slot of slots){const piece=slot==="weapon"?payload.weapon:payload.armor[slot];next[slot].equipment={key:`${piece.save_type}:${piece.save_id}`,label:`${slotNames[slot]} ID ${piece.save_id}`,value:{save_type:piece.save_type,save_id:piece.save_id,name:`ID ${piece.save_id}`,english:"",slots:0,confirmed:true}};next[slot].decorations=storedDecorations(piece.decorations)}setPieces(next);setSkill1({key:payload.charm.skill1_id,label:payload.charm.skill1_id===0?"无":`技能 ID ${payload.charm.skill1_id}`,value:{id:payload.charm.skill1_id,name:`ID ${payload.charm.skill1_id}`,english:""}});setSkill2({key:payload.charm.skill2_id,label:payload.charm.skill2_id===0?"无":`技能 ID ${payload.charm.skill2_id}`,value:{id:payload.charm.skill2_id,name:`ID ${payload.charm.skill2_id}`,english:""}});setCharmDecorations(storedDecorations(payload.charm.decorations))},[initial]);
  const complete=Boolean(slots.every(slot=>pieces[slot].equipment)&&dataVersion&&title.trim());
  function buildPayload():LoadoutPayload|null{if(!complete)return null;const skill1ID=skill1?.value.id??0;const skill2ID=skill2?.value.id??0;const piece=(slot:Slot)=>({save_type:pieces[slot].equipment!.value.save_type!,save_id:pieces[slot].equipment!.value.save_id,decorations:pieces[slot].decorations.filter(Boolean).map(item=>item!.value.save_id)});return{schema:"MH_LOADOUT",schema_version:1,game:"mh3g",data_version:dataVersion,name:title.trim(),gender,weapon:piece("weapon"),armor:{head:piece("head"),chest:piece("chest"),arms:piece("arms"),waist:piece("waist"),legs:piece("legs")},charm:{class_id:charmClass,slots:charmSlots,skill1_id:skill1ID,skill1_points:skill1ID===0?0:points1,skill2_id:skill2ID,skill2_points:skill2ID===0?0:points2,decorations:charmDecorations.filter(Boolean).map(item=>item!.value.save_id)}}}
  const previewKey=useMemo(()=>JSON.stringify({title,gender,pieces,charmClass,charmSlots,skill1:skill1?.key,skill2:skill2?.key,points1,points2,charmDecorations,dataVersion}),[title,gender,pieces,charmClass,charmSlots,skill1,skill2,points1,points2,charmDecorations,dataVersion]);
  useEffect(()=>setSaveError(""),[previewKey,remark,status,owner]);
  useEffect(()=>{const payload=buildPayload();if(!payload)return;const generation=++previewGeneration.current;const timer=window.setTimeout(()=>void api<{summary:Summary}>("/admin/loadouts/preview",{method:"POST",body:JSON.stringify({payload})}).then(value=>{if(generation===previewGeneration.current)setSummary(value.summary)}).catch(()=>{}),500);return()=>window.clearTimeout(timer)},[previewKey]);
  async function equipmentSearch(slot:Slot,keyword:string){const value=await api<{items:Candidate[]}>(`/admin/game-data/mh3g/equipment?slot=${slot}&q=${encodeURIComponent(keyword)}&limit=40`);return value.items.map(candidateOption)}
  async function decorationSearch(keyword:string){const value=await api<{items:Candidate[]}>(`/admin/game-data/mh3g/decorations?q=${encodeURIComponent(keyword)}&limit=40`);return value.items.map(candidateOption)}
  async function skillSearch(keyword:string){const value=await api<{items:NamedID[]}>(`/admin/game-data/mh3g/skills?q=${encodeURIComponent(keyword)}&limit=80`);return value.items.map(namedOption)}
  function updatePiece(slot:Slot,change:(piece:PieceState)=>PieceState){setPieces(current=>({...current,[slot]:change(current[slot])}))}
  async function save(){const payload=buildPayload();if(!payload){const missing=[] as string[];if(!title.trim())missing.push("配装名称");if(!dataVersion)missing.push("游戏数据版本");for(const slot of slots)if(!pieces[slot].equipment)missing.push(slotNames[slot]);const error=`无法保存：请填写或选择${missing.join("、")}。`;setSaveError(error);message.error(error);return}setSaveError("");setSaving(true);try{const body=JSON.stringify({owner_user_id:owner,remark,status,version:initial?.version??0,payload});await api(initial?`/admin/loadouts/${initial.id}`:"/admin/loadouts",{method:initial?"PUT":"POST",body});message.success(initial?"配装已更新":"配装已创建");onDone()}catch(error){const detail=error instanceof Error?error.message:"保存失败";setSaveError(detail);message.error(detail)}finally{setSaving(false)}}
  return <Space direction="vertical" size={16} style={{width:"100%"}}><Space><Button onClick={onCancel}>返回</Button><Typography.Title level={3} style={{margin:0}}>{initial?"编辑公开配装":"新建公开配装"}</Typography.Title></Space><Card><Form layout="vertical"><Row gutter={16}><Col span={8}><Form.Item label="配装名称" required><Input value={title} maxLength={40} showCount onChange={event=>setTitle(event.target.value)}/></Form.Item></Col><Col span={5}><Form.Item label="性别"><Select value={gender} onChange={setGender} options={[{value:"male",label:"男"},{value:"female",label:"女"}]}/></Form.Item></Col><Col span={5}><Form.Item label="发布状态"><Select value={status} onChange={setStatus} options={[{value:"published",label:"已发布"},{value:"hidden",label:"已隐藏"}]}/></Form.Item></Col><Col span={6}><Form.Item label="所有者"><Select showSearch optionFilterProp="label" value={owner} onChange={setOwner} options={users.filter(user=>user.status==="active").map(user=>({value:user.id,label:user.username}))}/></Form.Item></Col></Row><Form.Item label="备注"><Input.TextArea value={remark} maxLength={500} showCount rows={3} onChange={event=>setRemark(event.target.value)}/></Form.Item></Form></Card>
  {slots.map(slot=><Card key={slot} title={slotNames[slot]}><Row gutter={[12,12]}><Col span={9}><SearchSelect allowClear value={pieces[slot].equipment} placeholder={`输入${slotNames[slot]}名称或英文关键词`} search={keyword=>equipmentSearch(slot,keyword)} onClear={()=>updatePiece(slot,piece=>({...piece,equipment:null}))} onChange={option=>updatePiece(slot,piece=>({...piece,equipment:option}))}/></Col>{[0,1,2].map(index=><Col span={5} key={index}><SearchSelect allowClear value={pieces[slot].decorations[index]} placeholder={`装饰珠 ${index+1}`} search={decorationSearch} onClear={()=>updatePiece(slot,piece=>({...piece,decorations:piece.decorations.map((value,i)=>i===index?null:value)}))} onChange={option=>updatePiece(slot,piece=>({...piece,decorations:piece.decorations.map((value,i)=>i===index?option:value)}))}/></Col>)}</Row></Card>)}
  <Card title="护石"><Row gutter={[12,12]}><Col span={6}><Select style={{width:"100%"}} value={charmClass} onChange={setCharmClass} options={charmClasses.map(item=>({value:item.id,label:item.name}))}/></Col><Col span={4}><Select style={{width:"100%"}} value={charmSlots} onChange={setCharmSlots} options={[0,1,2,3].map(value=>({value,label:`${value} 孔`}))}/></Col><Col span={5}><SearchSelect value={skill1} placeholder="第1技能" search={skillSearch} onChange={setSkill1}/></Col><Col span={3}><InputNumber min={-128} max={127} value={points1} onChange={value=>setPoints1(value??0)}/></Col><Col span={5}><SearchSelect value={skill2} placeholder="第2技能" search={skillSearch} onChange={setSkill2}/></Col><Col span={3}><InputNumber min={-128} max={127} value={points2} onChange={value=>setPoints2(value??0)}/></Col></Row><Divider/><Row gutter={12}>{[0,1,2].map(index=><Col span={8} key={index}><SearchSelect allowClear value={charmDecorations[index]} placeholder={`护石装饰珠 ${index+1}`} search={decorationSearch} onClear={()=>setCharmDecorations(values=>values.map((value,i)=>i===index?null:value))} onChange={option=>setCharmDecorations(values=>values.map((value,i)=>i===index?option:value))}/></Col>)}</Row></Card>
  {summary&&<Card title="服务端实时计算"><Row gutter={16}><Col span={4}><Statistic title="基础防御" value={summary.base_defense}/></Col><Col span={4}><Statistic title="最大防御" value={summary.max_defense}/></Col><Col span={4}><Statistic title="孔位" value={`${summary.used_slots}/${summary.total_slots}`}/></Col><Col span={12}><Space wrap>{summary.skills.filter(skill=>skill.active_skill).map(skill=><Alert key={skill.skill_tree_id} type="success" showIcon message={`${skill.active_skill} (${skill.name} ${skill.points})`}/>)}</Space></Col></Row>{summary.diagnostics.length>0&&<><Divider/><Alert type="warning" showIcon message="该配装可以保存，但存在以下风险" description={<ul>{summary.diagnostics.map((item,index)=><li key={`${item.code}-${index}`}>{item.message} <code>{item.code}</code></li>)}</ul>}/></>}<Table size="small" pagination={false} rowKey="skill_tree_id" dataSource={summary.skills} columns={[{title:"技能系",dataIndex:"name"},{title:"点数",dataIndex:"points"},{title:"发动技能",dataIndex:"active_skill"}]}/></Card>}
  <Card><Space direction="vertical" style={{width:"100%"}}>{saveError&&<Alert type="error" showIcon message={saveError}/>}<Space><Button type="primary" loading={saving} onClick={()=>void save()}>保存配装</Button><Typography.Text type="secondary">不自然数据只提示，不会限制保存。</Typography.Text></Space></Space></Card></Space>
}
